---
language: python
python:
- "3.4"
env:
  matrix:
  # Production
  - secure: "wuDXA1AZsGIfKV+duwQsby3NAMCgTojarNblhweHIX+EyXTBnNqpeVXFJx1lFWnmRZu7guFNVe4kw3WRaR+VLDmeWCrJKLQkDAHvBbeuchFpqjf3A+DUvY23Uvejc+0+KTO622Lq1KuPlklq8nmxrwbDYlmqJr7WaiOKWK8HP1XiP92iyYWhqj7qPuCFaSDxCBAmEjGcpX8K+OEy+KK5X1CSlVOzWaxRZgHOAIWMxM9YbW978S9OBTq1zbCCqoXxM9+Zd3HF6lxtDLl+RLeRVzC8nJC9EqHpHhfOMztBRu5QsylP+fCaB1v2TjBP6svqHzj5FWNlfdY5cTulLH4/u51Uo3cC6gic+Z+CdDzUd6vhrvh+hwlCZ9z3ncVfSil+7kfTcWN33SJ8TqNryPGqFMPFXUoWvDnNL4Qbe3hevTISWmYavrVU/n30iFBUbQGwqwoCoPIzwGRdAbop9CpVcLVXDKB1bTT0rui+hSPchX/TD5hKloh0fyElsdaI0JviwesAD1cBl6lDErAk2SJ++AR8CPpwb7jjelSE3eszTbpwQpvIcEqStG8MKatI4tPc+jlI7UY3kI5XiQAMc6r1WBIa/HR4qBZDZDv5A2PTCnSaLO3MixjRiFe1pLM7qJ9rgrpsxARTQylhFfhh1oXFq9QYePV64rEq4bVkhCmQZjY="
  # Staging
  - secure: "e442KwletkS1wB/SPvIRU4TKbcpD3L0OacDqOLmeYa+Il2xeQqtQ0VU9lr05pxG+mYpAg29wNaKg1OrW2NI3GkfbISz2j3TVcweTGtXk0/ZVDGbVcNgBpXVXDzPo0Pe1LxZbPJbaYOm24Z6gC2Hq/sue2ha6RqHJVESQ9lMwZf+PVNJtxD64/MHDn265KmUzUnIsAeBCmF7IpzTJ7uja43utc9CVxmK7ar1D8GsrWDvY0phvnjwXwBpaJvxBXjmdABG1OdDV0QYrfPb4R2jCJb4gySg0fsOoMWm5oa7gx0Xh5EzWqJv3Qa12xphCnc4dX53bnh9VymUK4vAd0yu6zob5MpBNC7Ya7uyA0Sd8Oq9R9Ms2PNA7DG27OAK+YnqSM69E2cuR5GGbNiQKqAzZDjoZwKjSsoUWXTIKqjHUum/XsL6FJkOefsM+UD9iou4LrkqQKqlAZPRBgnYriWJUg35O0/d/Y//9xPPU3ND1OYyrX2Fyp8WU+fOKcekSydsN04YCKGPq5WPGkHxgIWuNv/F+h3IgyqMmyRruxpGvUUARyyxmSiQRH/6VOFvyWxXnJy/QBHI9/KVDU0FDbyYM90uY41Nw0JzdY3APqi9sXaHtxH8oBD9I8pNqE2CQ5U5Wgp3lQ71Hz1i+8TKswMsm1KtT19GzkXPLLpbNd5MyUE0="
install:
- "pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst"
script:
- 'echo "Submitting content: ${DESC:-nowhere}"'
- deconst-preparer-sphinx
